### ISSUE TITLE
Mods, die eine ID haben, die weniger als 10 Zeichen haben, können nicht installiert werden

### ISSUE THREAD

**Issue by xRaid96** [Lacrimosa99/Easy-WI-Teamspeak-Updater#2]
In der INSTALL() Funktion wird vorausgesetzt, dass die Mod ID 10 Zeichen lang ist. Es gibt aber durchaus auch Mods, die eine ID haben, die nur 9 Zeichen lang ist. Bsp. hier: http://steamcommunity.com/sharedfiles/filedetails/?id=972887420

Wenn ich diesen Mod installieren will, bekomme ich einen invalid input error.

**Comment by Lacrimosa99** [comment]
TS3 Updater hat keine IDs.
