### ISSUE TITLE
STRG + C löscht die temp Datei leider nicht

### ISSUE THREAD

**Issue by xRaid96** [Lacrimosa99/Easy-WI-Teamspeak-Updater#3]
Wenn man in dem Script STRG + C zum canceln drückt, wird die temp Datei im easy-wi Ordner leider nicht gelöscht und das Script meckert rum, dass es bereits laufen würde.

**Comment by Lacrimosa99** [comment]
Auch hier... ein STRG + C ist nicht im Script bedacht, da man Shell Scripte nicht so abbrechen sollte!
